<?php
require dirname(__FILE__).'/'.'power.php';
require dirname(__FILE__).'/'.'session.php';
use usualtool\Lib\Inc;
use usualtool\Lib\Data;
use usualtool\Lib\Route;
if($utype!=99999):
    Inc::GoUrl("-1","权限不足!"); 
endif;
$l=$_GET["l"];
$c=$_GET["c"];
$payment=Data::QueryData("cms_pay","","","","1")["querydata"];
$connect=Data::QueryData("cms_connect","","","","1")["querydata"];
$app->Runin(array("webplace","set","l","c","payment","connect"),array("管理设置",$set,$l,$c,$payment,$connect));
$app->Open("my_admin_set.cms");
if($_GET["do"]=="update"){
    $id=Inc::SqlCheck($_POST["id"]);
    $rate=Inc::SqlCheck($_POST["rate"]);
    $cookname=Inc::SqlCheck($_POST["cookname"]);
    if(Data::UpdateData("forum_set",array("rate"=>$rate,"cookname"=>$cookname),"id='$id'")):
        Inc::GoUrl(Route::Link("forum","my_admin_set"),"保存设置成功!");
    else:
        Inc::GoUrl("-1","保存设置失败!");
    endif;
}
if($_GET["do"]=="payment"){
    $id=Inc::SqlCheck($_POST["id"]);
    $ali_appid=Inc::SqlCheck($_POST["ali_appid"]);
    $ali_private_key=urlencode(Inc::SqlCheck($_POST["ali_private_key"]));
    $ali_public_key=urlencode(Inc::SqlCheck($_POST["ali_public_key"]));
    $ali_notify_url=Inc::SqlCheck($_POST["ali_notify_url"]);
    $ali_return_url=Inc::SqlCheck($_POST["ali_return_url"]);
    $wx_appid=Inc::SqlCheck($_POST["wx_appid"]);
    $wx_mchid=Inc::SqlCheck($_POST["wx_mchid"]);
    $wx_key=Inc::SqlCheck($_POST["wx_key"]);
    $wx_secert=Inc::SqlCheck($_POST["wx_secert"]);
    $wx_notify_url=Inc::SqlCheck($_POST["wx_notify_url"]);
    $pp_mod=Inc::SqlCheck($_POST["pp_mod"]);
    $pp_clientid=Inc::SqlCheck($_POST["pp_clientid"]);
    $pp_secret=Inc::SqlCheck($_POST["pp_secret"]);
    $pp_return_url=Inc::SqlCheck($_POST["pp_return_url"]);
    $pp_notify_url=Inc::SqlCheck($_POST["pp_notify_url"]);
    $url_ok=Inc::SqlCheck($_POST["url_ok"]);
    $url_no=Inc::SqlCheck($_POST["url_no"]);
    if(!empty($id)){
        if($l=="alipay"):
            $sql=Data::UpdateData("cms_pay",array(
                "ali_appid"=>$ali_appid,
                "ali_private_key"=>$ali_private_key,
                "ali_public_key"=>$ali_public_key,
                "ali_notify_url"=>$ali_notify_url,
                "ali_return_url"=>$ali_return_url),"id='$id'");
        elseif($l=="wechat"):
            $sql=Data::UpdateData("cms_pay",array(
                "wx_appid"=>$wx_appid,
                "wx_mchid"=>$wx_mchid,
                "wx_key"=>$wx_key,
                "wx_secert"=>$wx_secert,
                "wx_notify_url"=>$wx_notify_url),"id='$id'");
        elseif($l=="paypal"):
            $sql=Data::UpdateData("cms_pay",array(
                "pp_mod"=>$pp_mod,
                "pp_clientid"=>$pp_clientid,
                "pp_secret"=>$pp_secret,
                "pp_return_url"=>$pp_return_url,
                "pp_notify_url"=>$pp_notify_url),"id='$id'");
        elseif($l=="url"):
            $sql=Data::UpdateData("cms_pay",array(
                "url_ok"=>$url_ok,
                "url_no"=>$url_no),"id='$id'");
        endif;
    }else{
        if($l=="alipay"):
            $sql=Data::InsertData("cms_pay",array(
                "ali_appid"=>$ali_appid,
                "ali_private_key"=>$ali_private_key,
                "ali_public_key"=>$ali_public_key,
                "ali_notify_url"=>$ali_notify_url,
                "ali_return_url"=>$ali_return_url));
        elseif($l=="wechat"):
            $sql=Data::InsertData("cms_pay",array(
                "wx_appid"=>$wx_appid,
                "wx_mchid"=>$wx_mchid,
                "wx_key"=>$wx_key,
                "wx_secert"=>$wx_secert,
                "wx_notify_url"=>$wx_notify_url));
        elseif($l=="paypal"):
            $sql=Data::InsertData("cms_pay",array(
                "pp_mod"=>$pp_mod,
                "pp_clientid"=>$pp_clientid,
                "pp_secret"=>$pp_secret,
                "pp_return_url"=>$pp_return_url,
                "pp_notify_url"=>$pp_notify_url));
        elseif($l=="url"):
            $sql=Data::InsertData("cms_pay",array(
                "url_ok"=>$url_ok,
                "url_no"=>$url_no));                
        endif;
    }
    if($sql):
        Inc::GoUrl(Route::Link("forum","my_admin_set","l=".$l)."#payment","操作成功!");
    else:
        Inc::GoUrl("-1","操作失败!");
    endif;
}
if($_GET["do"]=="connect"){
    $id=Inc::SqlCheck($_POST["id"]);
    $qq_appid=Inc::SqlCheck($_POST["qq_appid"]);
    $qq_appkey=Inc::SqlCheck($_POST["qq_appkey"]);
    $qq_reurl=Inc::SqlCheck($_POST["qq_reurl"]);
    $wb_appid=Inc::SqlCheck($_POST["wb_appid"]);
    $wb_appkey=Inc::SqlCheck($_POST["wb_appkey"]);
    $wb_reurl=Inc::SqlCheck($_POST["wb_reurl"]);
    $wx_appid=Inc::SqlCheck($_POST["wx_appid"]);
    $wx_appkey=Inc::SqlCheck($_POST["wx_appkey"]);
    $wx_reurl=Inc::SqlCheck($_POST["wx_reurl"]);
        if($c=="qq"):
            Data::UpdateData("cms_connect",array("qq_appid"=>$qq_appid,"qq_appkey"=>$qq_appkey,"qq_reurl"=>$qq_reurl),"id='$id'");
        endif;
        if($c=="weibo"):
            Data::UpdateData("cms_connect",array("wb_appid"=>$wb_appid,"wb_appkey"=>$wb_appkey,"wb_reurl"=>$wb_reurl),"id='$id'");
        endif;
        if($c=="wechat"):
            Data::UpdateData("cms_connect",array("wx_appid"=>$wx_appid,"wx_appkey"=>$wx_appkey,"wx_reurl"=>$wx_reurl),"id='$id'");
        endif;
        Inc::GoUrl(Route::Link("forum","my_admin_set","c=".$c)."#connect","保存成功!");
}